import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

/** Embed a standalone client in the agent build; never compile on the service host. */
export async function buildClientBundle() {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("./main.mts", import.meta.url))],
    bundle: true,
    packages: "bundle",
    platform: "node",
    format: "esm",
    target: "node24",
    minify: true,
    write: false,
    metafile: true,
    logLevel: "silent",
    banner: {
      js: 'import { createRequire as __clientCreateRequire } from "node:module"; const require = __clientCreateRequire(import.meta.url);',
    },
  });
  const output = result.outputFiles[0];
  if (!output) throw new Error("No client bundle was produced.");
  for (const file of Object.values(result.metafile.outputs))
    for (const dependency of file.imports)
      if (dependency.external && !dependency.path.startsWith("node:"))
        throw new Error(
          `Client bundle has an external dependency: ${dependency.path}`,
        );
  const destination = fileURLToPath(
    new URL("./generated/bundle.js", import.meta.url),
  );
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(
    destination,
    `// Generated by client/build.mts. Do not edit.\nexport const clientBundle = ${JSON.stringify(output.text)};\n`,
  );
  return output.text;
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url)
  await buildClientBundle();
